name: hookified_infinite_scroll_pagination
description: flutter_hooks support for infinite_scroll_pagination (with updated deps)
version: 0.1.1
homepage: https://github.com/KRTirtho/hookified/tree/main/packages/hookified_infinite_scroll_pagination
issue_tracker: https://github.com/KRTirtho/hookified/issues

repository: https://github.com/KRTirtho/hookified

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  infinite_scroll_pagination: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
